meta_url: https://onsdigital.github.io/sdg-data/en/meta/all.json
disag_url: https://sdgdata.gov.uk/sdg-data/disaggregation-by-indicator-report.csv
required_cols: 
  - other_info
  - data_non_statistical
  - national_geographical_coverage
  - reporting_status
proxy_terms:
  - proxy indicator
  - proxy measure
  - used as an approximation
  - suitable proxy
  - used as a proxy
uk_terms:
  - United Kingdom
  - UK
  - England, Scotland, Wales, Northern Ireland
geo_disag_terms:
  - Region
  - Country
  - Local Authority
outfile: output.csv
suitability_test:
  data_non_statistical: False
  national_geographical_coverage: United Kingdom
  reporting_status: Completed
  proxy_indicator: False
  only_uk_data: True
  geo_disag: False