meta_url: https://sdgdata.gov.uk/sdg-data/en/meta/all.json
disag_url: https://sdgdata.gov.uk/sdg-data/disaggregation-by-indicator-report.csv
dsd_url: https://unstats.un.org/sdgs/files/SDG_DSD_MATRIX.1.4.xlsm
required_cols: 
  - other_info
  - data_non_statistical
  - national_geographical_coverage
  - reporting_status
required_disag_cols:
  - Indicator
  - geo_disag
proxy_terms:
  - proxy indicator
  - proxy measure
  - used as an approximation
  - suitable proxy
  - used as a proxy
uk_terms:
  - United Kingdom
  - UK
  - England, Scotland, Wales, Northern Ireland
geo_disag_terms:
  - Region
  - Country
  - Local Authority
meta_outfile: meta_data.csv
disag_outfile: disag.csv
sdg_cols_outfile : SDG_column_names.csv
manual_excel_file_name: sdg_sdmx_colnames-manual.xlsx
suitability_test:
  data_non_statistical: false
  national_geographical_coverage: "United Kingdom"
  reporting_status: "complete"
  proxy_indicator: false
  only_uk_data: true
  geo_disag: false
2020indicators:
  - 13-2-2
  - 17-5-1
  - 17-6-1
sort_order:
  - goal
  - target
  - indicator
